baseurl: "/docs" # the subpath of your site, e.g. /blog/

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
  - no_intra_emphasis
  - fenced_code_blocks
  - autolink
  - tables
  - with_toc_data
  - footnotes

collections:
  repos:
    output: true
    permalink: repos/:title.html
  github_accounts:
    output: true
    permalink: github-accounts/:path/index.html