baseurl: "/docs" # the subpath of your site, e.g. /blog/

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - footnotes

collections:
  articles:
    output: true
    permalink: articles/:title.html
  categories:
    output: true
    permalink: categories/:path/index.html